### ISSUE TITLE
Pages To Migrate

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#1]
The following pages are listed to migrate.

- [x] [https://ihsvirtualexperience.com/](https://main--takeda-ihs--hlxsites.hlx.llive/)
  - Before: 56*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live/b8vnap7xo9?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/products/](https://main--takeda-ihs--hlxsites.hlx.live/products/)
  - Before: 66*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-products/weudykrohx?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/gammagard-liquid/](https://main--takeda-ihs--hlxsites.hlx.live/products/gammagard-liquid)
  - Before: 55*
  - After: [99, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-products-gammagard-liquid/gi39ybx4yi?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/gammagard-sd/](https://ihsvirtualexperience.com/gammagard-sd/)
  - Before: 68*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-products-gammagard-sd/60geadguyf?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/hyqvia/](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-products-hyqvia/pv8m5lm0g4?form_factor=mobile)
  - Before: 62*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-products-hyqvia/pv8m5lm0g4?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/cuvitru/](https://main--takeda-ihs--hlxsites.hlx.live/products/cuvitru)
  - Before: 56*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-products-cuvitru/dlvtatltkb?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/flexbumin/](https://main--takeda-ihs--hlxsites.hlx.live/products/flexbumin)
  - Before: 55*
  - After: [99, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-products-flexbumin/nua0edpdg2?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/glassia/](https://main--takeda-ihs--hlxsites.hlx.live/products/glassia)
  - Before: 49*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-products-glassia/65ab7xpidj?form_factor=mobile)
- [ ] [https://ihsvirtualexperience.com/aralast/](https://main--takeda-ihs--hlxsites.hlx.live/products/aralast)
  - Before: 61*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-products-aralast/wuw0dpwczh?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/programs/](https://main--takeda-ihs--hlxsites.hlx.live/programs/)
  - Before: 55*
  - After: [99, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-programs/wytrphjpvw?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/population-health/](https://main--takeda-ihs--hlxsites.hlx.live/programs/population-health)
  - Before: 55*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-programs-population-health/1bo2fs8r2h?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/stewardship-series/](https://main--takeda-ihs--hlxsites.hlx.live/programs/stewardship-series)
  - Before: 55*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-programs-stewardship-series/l8bkarxk7h?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/service/](https://main--takeda-ihs--hlxsites.hlx.live/service/)
  - Before: 69*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-service/7iyn8uy22m?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/onepath/](https://main--takeda-ihs--hlxsites.hlx.live/service/onepath)
  - Before: 55*
  - After: [98, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-service-onepath/cnl5cwhv9w?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/myigsource/](https://main--takeda-ihs--hlxsites.hlx.live/service/myigsource)
  - Before: 69*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-service-myigsource/sqv4copgun?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/hello-programs/](https://main--takeda-ihs--hlxsites.hlx.live/service/hello-programs)
  - Before: 87*
  - After: [99, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-service-hello-programs/vhufdnrzvy?form_factor=mobile)
- [x] [https://ihsvirtualexperience.com/manufacturing/](https://main--takeda-ihs--hlxsites.hlx.live/manufacturing/)
  - Before: 56*
  - After: [100, 100](https://pagespeed.web.dev/analysis/https-main--takeda-ihs--hlxsites-hlx-live-manufacturing/acz5m4uwf3?form_factor=mobile)

*Note: All before page scores are based on Chrome Lighthouse plugin due to the PSI lab blocked by the disclaimer modal.

**Comment by DanCollinz** [comment]
There are edits and updates to pages, including removing some pages and deleting page sections, and copy updates. See spreadsheet in the [teams IHS group](https://teams.microsoft.com/l/team/19%3acmWLw02CzoUPr9Uz_h1s5W0ocxjZDD-DFXtrGF-hMbc1%40thread.tacv2/conversations?groupId=38cc410b-1990-48ce-bc73-d73cfd17bcf8&tenantId=57fdf63b-7e22-45a3-83dc-d37003163aae).

**Comment by DanCollinz** [comment]
Note for contracting page:  No form for phase 1. Madeline to provide copy for the page

**Comment by OcmCollins** [comment]
done
