### ISSUE TITLE
Floating Image

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#10]
<img width="703" alt="Floating_Image" src="https://github.com/hlxsites/takeda-ihs/assets/6520270/85a4e40b-7fbf-41a7-9c22-59cb4b22224d">

**Comment by DanCollinz** [comment]
looking into this rn. Is there a way to self assign issues?

**Comment by bstopp** [comment]
Take a look at this for an example of the solution: 

https://github.com/hlxsites/hsf-commonmoves/tree/main/blocks/floating-images

Floating images are based on a `section metadata` flag that says the image should float one direction or the other. Here's what that looks like from an authoring perspective. (Draft page is in Goolge Drive.)

<img width="350" alt="floating-images_-_Google_Docs" src="https://github.com/hlxsites/takeda-ihs/assets/6520270/8b817c84-2301-4553-85a8-860d6e1344de">

**Comment by DanCollinz** [comment]
question: I was thinking this is a two column table, with the class image right or image left, "column(image-right)or column(i
![Screenshot 2023-06-14 at 10 59 16 AM](https://github.com/hlxsites/takeda-ihs/assets/757431/0dda5adb-1df3-4d83-b8b9-935afc54c0d5)
mage-left)"
![Screenshot 2023-06-14 at 11 01 22 AM (2)](https://github.com/hlxsites/takeda-ihs/assets/757431/90f33cc5-3818-4195-a2fb-27b24071e015)

**Comment by DanCollinz** [comment]
Im not advocating for one way or another, just trying to learn about how your thinking about this

**Comment by bstopp** [comment]
Closed via #72
