### ISSUE TITLE
Services Landing Page  Account management Service Section

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#111]
Not sure if we have a solution. For now I just used an image. Given the lifespan of the site I think this is ok

With Image: https://main--takeda-ihs--hlxsites.hlx.page/service/

Live page: https://ihsvirtualexperience.com/service/

**Comment by bstopp** [comment]
I can probably get this working in a couple of hours if you'd like it done?

**Comment by DanCollinz** [comment]
> I can probably get this working in a couple of hours if you'd like it done?

I dont think its worth it. Lets leave for later if a reason comes up

**Comment by bstopp** [comment]
Completed using image.
