### ISSUE TITLE
Unordered List Columns

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#12]
<img width="673" alt="Visit_Takeda_s_NICA_Virtual_Experience" src="https://github.com/hlxsites/takeda-ihs/assets/6520270/115070eb-38fd-4c39-91f1-06844927212e">

Found here: https://ihsvirtualexperience.com/population-health/

**Comment by DanCollinz** [comment]
for this issue, so you can sanity check  an approach...I think this could be a column block with a class like columns(some-clever-classname) then the column table has two columns. one where the left image is and then on the right column, an H tag with the list underneath. Or maybe what you want is just a new block, something like, multi-ul-block, that has unordered lists for the content....

**Comment by bstopp** [comment]
Actually - i was thinking of ignoring the image and the title all together.

The section overall is a `floating image` which will keep image on the left. The title on the right is free-form text, not a block. which means the only thing that needs to be blocked (or not depending) is the three red border text items.

**Comment by bstopp** [comment]
New approach - see slack for discussion.

**Comment by lwintch** [comment]
PR #43 active, but waiting for global styles before refactoring.
