### ISSUE TITLE
Nav Breaks When there isnt a Utility Nav

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#121]
Delete the top two entries in the nav, the utility links, see that the nav doesn't show at all. Since for phase 1a we dont need the pages currently in the utility section e need a way to show the nav without the utility ....
I took a shot at a fix here: https://no-utility-nav-use-case-mod--takeda-ihs--hlxsites.hlx.page/

**Comment by bstopp** [comment]
Fixed with content edits.

Leave one empty list item to display the nav without any content.
