### ISSUE TITLE
Who We Are Block on HomePage Display is broken

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#122]
see screenshot 
![Screenshot 2023-08-15 at 12 53 36 PM](https://github.com/hlxsites/takeda-ihs/assets/757431/687adb11-e1c8-4d35-94a2-0ff27516416a)

**Comment by bstopp** [comment]
Fixed with updating Card variation to `icon cta` rather than `icon`.

This was a new variation added recently to support another card style that contains icons, but no links.
