### ISSUE TITLE
Missing quote box on  Population Health page

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#132]
At page bottom of live site there is a quote with a ref.  https://takvirtualexperience.com/population-health/

not sure if we can use the same quote box on the HP,....
![Screenshot 2023-08-15 at 5 39 18 PM](https://github.com/hlxsites/takeda-ihs/assets/757431/53c2747d-781e-4a88-bb62-c49da20e2bf7)

**Comment by lwintch** [comment]
Are we ok to close this issue, if that's the consensus? @DanCollinz

**Comment by lwintch** [comment]
Closing as this is no longer needed.
