### ISSUE TITLE
Services Hello Page Doesnt have Logo or BG image

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#136]
This is such an edge case......but ....
The live page has a gradient background and thier isnt a logo. In place of a logo, there is text. The picture position in our block wont appear unless there is an image. I think we need an alternative mode where we dont have an image but want to use text, like an <h1>
![Screenshot 2023-08-16 at 9 25 24 AM](https://github.com/hlxsites/takeda-ihs/assets/757431/e2aa4258-d4ae-47fd-940d-bb2a6821aae5)

links to pages:

new: https://main--takeda-ihs--hlxsites.hlx.page/service/hello-programs
Live: https://ihsvirtualexperience.com/hello-programs/

**Comment by lwintch** [comment]
Closing as per Dan's recommendation.
