### ISSUE TITLE
Research CLS on these pages:

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#148]
Scores are still 100, but would like to know why these are not closer to 0.

* [Products Landing](https://main--takeda-ihs--hlxsites.hlx.live/products/?lighthouse=on)
* [Gammagard SD](https://main--takeda-ihs--hlxsites.hlx.live/products/gammagard-sd?lighthouse=on)
* [Flexbumin](https://main--takeda-ihs--hlxsites.hlx.live/products/flexbumin?lighthouse=on)

**Comment by rrusher** [comment]
Not having a CLS of zero appears to be primarily caused by the menu.
<img width="727" alt="Screenshot 2024-01-19 at 12 52 14 PM" src="https://github.com/hlxsites/takeda-ihs/assets/6796243/8c3a3fdf-049b-4f25-9ba2-df1b64ba063b">

**Comment by OcmCollins** [comment]
non issue, old site
