### ISSUE TITLE
Phase 1B Section Section need to set BG Image and Content Wrapper Bump UP

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#150]
In the new design the sections have a background image and the content sticks up into the image....

<img width="847" alt="Screenshot 2023-10-30 at 2 49 33 PM" src="https://github.com/hlxsites/takeda-ihs/assets/757431/3d4ff678-f08e-4e89-a816-984b0d22dabc">

**Comment by OcmCollins** [comment]
done
