### ISSUE TITLE
Phase 1B New Style for Disclaimer Modal.....

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#151]
Need to change black background to opaque, add a second button dimensions and backgound of disclaimer container are slightly different . Add X to close in top right corner....
Got a start on this here: [phase1b-test](https://phase-1b-test--takeda-ihs--hlxsites.hlx.page)
desktop
<img width="765" alt="Screenshot 2023-10-30 at 2 51 07 PM" src="https://github.com/hlxsites/takeda-ihs/assets/757431/94fbfd11-83e4-4121-af22-db93654b55e6">

mobile
<img width="501" alt="Screenshot 2023-10-30 at 3 04 34 PM" src="https://github.com/hlxsites/takeda-ihs/assets/757431/e6b03e47-6c2f-4055-8872-380b7cd4e673">

**Comment by OcmCollins** [comment]
looks good
