### ISSUE TITLE
Phase 1B Update CTA Cards to Match New Design

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#154]
here is a screenshot:
<img width="712" alt="Screenshot 2023-10-30 at 2 50 13 PM" src="https://github.com/hlxsites/takeda-ihs/assets/757431/582dd9cb-e4d3-4b30-8c34-122c15a8e338">

link to the cards Authoring Guide: https://main--takeda-ihs--hlxsites.hlx.page/author-guide/blocks/cards

**Comment by OcmCollins** [comment]
done
