### ISSUE TITLE
Phase 1B Update style for floating image block

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#155]
The new design is pretty much the same, really just need to remove the red let border..here is a link to the[ floating image block:](uhttps://aem-assets--takeda-ihs--hlxsites.hlx.page/author-guide/sections/floating-imagesrl)

new design

<img width="1436" alt="Screenshot 2023-11-01 at 12 52 31 PM" src="https://github.com/hlxsites/takeda-ihs/assets/757431/5232caca-072c-4e55-9523-cd6f7b278177">

old design
![Screenshot 2023-11-01 at 12 53 14 PM](https://github.com/hlxsites/takeda-ihs/assets/757431/dac1f03d-85b7-44ee-beb6-3f0e24b0eabf)

link to a page using the[ floating image block](https://main--takeda-ihs--hlxsites.hlx.page/programs/)

**Comment by OcmCollins** [comment]
done
