### ISSUE TITLE
Phase 1B Update button style

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#156]
pretty simple blow I'll past a screenshot of the new button and below the old one:

new button style:
<img width="597" alt="Screenshot 2023-11-01 at 12 59 42 PM" src="https://github.com/hlxsites/takeda-ihs/assets/757431/0223cc31-bfc2-4603-ab73-b584753a1635">

Old Button
![Screenshot 2023-11-01 at 1 00 21 PM](https://github.com/hlxsites/takeda-ihs/assets/757431/f9b5fdb2-6b77-4018-a7dd-e77e714387d6)

**Comment by rrrragas** [comment]
@DanCollinz  looks like it is already taken care in "phase-two-redo" branch. Please let me know if anything more to be fixed
https://phase-two-redo--takeda-ihs--hlxsites.hlx.page/author-guide/style-guide

**Comment by OcmCollins** [comment]
this is done
