### ISSUE TITLE
Phase1B-Site-leave-For Healthcare-pros-only- modal.

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#157]
For the healthcare-pro-selector modal. It is working now, just needs styling.....it is presented to new users, and creates a cookie to suppress on next visits. For the site leave modal: Presume the modal is triggered by some, at this time unknown URL...adding a screenshot....
<img width="979" alt="Screenshot 2023-11-27 at 11 54 52 AM" src="https://github.com/hlxsites/takeda-ihs/assets/757431/14d3f87e-b58c-48e4-a649-26ccc60e715b">
<img width="874" alt="Screenshot 2023-11-27 at 11 58 25 AM" src="https://github.com/hlxsites/takeda-ihs/assets/757431/1f809459-4645-4b9b-94ee-6e382328f8fb">

**Comment by OcmCollins** [comment]
done
