### ISSUE TITLE
Phase 1B Remove hardcoded text from hero card

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#158]
Madeline asked that I remove the hardcoded text in the button that says download. There isnt a download anymore, it links to another site. And the button is clickable and we can write whatever we want in the links .

from this:
![Screenshot 2023-12-01 at 9 29 09 AM](https://github.com/hlxsites/takeda-ihs/assets/757431/c56c9cc0-bf78-4421-896f-54aa6dec140b)
 to this:
![Screenshot 2023-12-01 at 9 29 09 AM](https://github.com/hlxsites/takeda-ihs/assets/757431/ab732727-d1d3-4401-b080-474834b0f6e5)

**Comment by OcmCollins** [comment]
done
