### ISSUE TITLE
Product Cards vertical and horizontal

### ISSUE THREAD

**Issue by OcmCollins** [hlxsites/takeda-ihs#162]
There are two presentations for these vertical and horizontal. We have several card types already created. I think the Profile Variation card may be a good one to modify.  Its in the Author Guide found [here](https://main--takeda-ihs--hlxsites.hlx.page/author-guide/blocks/cards)

<img width="875" alt="Screenshot 2024-01-21 at 6 56 45 PM" src="https://github.com/hlxsites/takeda-ihs/assets/125283156/44c7e4e8-782d-4f46-80c5-452b72504a69">

vertical

<img width="299" alt="Screenshot 2024-01-21 at 6 49 46 PM" 
src="https://github.com/hlxsites/takeda-ihs/assets/125283156/4744c067-7591-44a3-8e64-13c92af76e1d">

horizontal
<img width="327" alt="Screenshot 2024-01-21 at 6 54 34 PM" src="https://github.com/hlxsites/takeda-ihs/assets/125283156/e6e41d4c-a8b2-460d-8e2d-f6f54b5e0432">

**Comment by rrrragas** [comment]
@DanCollinz  for quick testing I have updated the product card block code in my local. can you please take a look and provide your view on this

![screencapture-localhost-3000-drafts-sagar-product-card-redo-2024-01-25-18_08_54](https://github.com/hlxsites/takeda-ihs/assets/122023336/92ea892f-2a50-4913-b4ae-d114beda2f44)

**Comment by OcmCollins** [comment]
done
