### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#17]
<img width="666" alt="Coiumns" src="https://github.com/hlxsites/takeda-ihs/assets/6520270/3bf791fd-2e7e-4d37-9382-20afb94d8b8d">

**Comment by DanCollinz** [comment]
These columns look like card blocks?  Do cards seem like a good place to start for this?

**Comment by bstopp** [comment]
> These columns look like card blocks? Do cards seem like a good place to start for this?

Lance is already working on this and has a semi-functional state.

**Comment by lwintch** [comment]
Merged here: https://github.com/hlxsites/takeda-ihs/pull/24
