### ISSUE TITLE
Programs Landing Page Content/Blocks

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#34]
* #2 
* #3 
* Section - border-between, 50-50 layout, floating image
  * Free Form Text
* Section - quartz background, 
  * #17 (75-25 layout)
* #6

**Comment by DanCollinz** [comment]
Primary Immunodeficiency change to Rare Disease 
Remove get in touch section

**Comment by DanCollinz** [comment]
this is done:https://main--takeda-ihs--hlxsites.hlx.page/programs/population-health
