### ISSUE TITLE
Stewardship Series Content/Blocks

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#36]
* #2 
* #3 (Dark Grey background)
* Section - #14 
  * #13 
* Section
  * #13 
* #6

**Comment by DanCollinz** [comment]
Remove all expert cards and entire "Meet Our Experts" section

**Comment by DanCollinz** [comment]
this is done:https://main--takeda-ihs--hlxsites.hlx.page/programs/stewardship-series
