### ISSUE TITLE
Service Landing Page Content/Blocks

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#37]
* #2 
* #3 (light grey background)
* Section - gray gradient background
  * #13 (icon variation)
* Section
  * #13 
* Section - quartz background
  * #17 (75-25 layout)
* #6

**Comment by DanCollinz** [comment]
Schedule a meeting block should be removed

**Comment by DanCollinz** [comment]
This is done: But we will need a simple block for the more information section if we didnt already built it. See screenshot, its slightly diff layout for phase 1b
![Screenshot 2023-08-21 at 4 03 32 PM](https://github.com/hlxsites/takeda-ihs/assets/757431/4ac2ea4a-f41f-418f-9efd-5cd77012bc9c)

**Comment by bstopp** [comment]
Are you saying you want this block implemented?

<img width="634" alt="Cursor_and_Visit_Takeda_s_NICA_Virtual_Experience" src="https://github.com/hlxsites/takeda-ihs/assets/6520270/46c61d9e-8654-4abf-a36a-09298f794285">

**Comment by DanCollinz** [comment]
We dont need to build that block the request info block above is all we need

**Comment by OcmCollins** [comment]
done
