### ISSUE TITLE
Manufacturing Page Content/Blocks

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#39]
* #2 
* #3 (light grey gradient background)
* Section - grey gradient background
  *  #16 
* Section
  * Free Form Text
  * #17 
  * Free Form Text
  * #17 (75-25 layout)
* #6  

Found here: https://ihsvirtualexperience.com/manufacturing/

**Comment by DanCollinz** [comment]
Note: none of the video blocks carry over in the Migration. For the resource block, see if we can add it as the fourth card in the Column (triple-aim )

**Comment by DanCollinz** [comment]
this is done: https://main--takeda-ihs--hlxsites.hlx.page/manufacturing/
