### ISSUE TITLE
Nav Desktop Width 

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#47]
At desktop viewports, the nav shouldn't be larger than the main content section. The box shadow and background color stretching is fine, but should try to bring this in.

<img width="1281" alt="Menubar_and_Hero__product__gamma-guard_" src="https://github.com/hlxsites/takeda-ihs/assets/6520270/4a9b1d47-3e91-4f1e-9ee5-9f27c29fbb4e">

**Comment by lwintch** [comment]
@bstopp , further down the page, we do have full width content.  Should we bring that in also?

![image](https://github.com/hlxsites/takeda-ihs/assets/5343448/782aa136-d390-4844-aa4b-5ef0fc7daefe)

**Comment by bstopp** [comment]
Yes

**Comment by lwintch** [comment]
Cool, I'm on it.

**Comment by OcmCollins** [comment]
non issue
