### ISSUE TITLE
Gammaguard-liquid sub headline not showing

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#75]
the subheading: (Based on aggregate analysis) is no showing in the hero, under the title.

![Screenshot 2023-07-27 at 10 03 21 AM](https://github.com/hlxsites/takeda-ihs/assets/757431/974146a9-e642-48b9-b790-db0279e8bbec)
![Screenshot 2023-07-27 at 10 03 56 AM](https://github.com/hlxsites/takeda-ihs/assets/757431/c373380c-3704-4141-b80f-e0ea85ed7676)

**Comment by bstopp** [comment]
This was an authoring issue and has been fixed.
