### ISSUE TITLE
Gammaguard SD and Liquid Logo not alined left with title and sub title

### ISSUE THREAD

**Issue by DanCollinz** [hlxsites/takeda-ihs#78]
![Screenshot 2023-07-27 at 10 38 28 AM](https://github.com/hlxsites/takeda-ihs/assets/757431/f33991ee-1cb2-4c00-b4f2-5eede827fd29)

**Comment by bstopp** [comment]
This is actually an issue with the image. The image itself has padding built into it on the left. 

Here are the images used to create the product heros. 
![GammaS_D_Logo](https://github.com/hlxsites/takeda-ihs/assets/6520270/9e4a5af2-902b-45f2-85d6-f81168977698)
![GammaLq_Logo](https://github.com/hlxsites/takeda-ihs/assets/6520270/e32f90b0-0cea-4ffa-8f73-4b99abe9f6c8)
